import type { BgmTrack } from "./bgmTypes";

const PLACEHOLDER_LICENSE = "Metadata placeholder only. Bundled demo audio should be replaced with licensed files.";

export const builtInTracks: BgmTrack[] = [
  {
    id: "night-suspense",
    title: "Dear John",
    source: "built-in",
    fileRef: "/bgm/DearJohn.mp3",
    genres: ["释怀", "感情流", "日常"],
    moods: ["释然", "轻松", "孤独"],
    scenes: ["夕阳", "独行", "告别"],
    energy: 0.4,
    darkness: 0.85,
    warmth: 0.2,
    tempo: "slow",
    complexity: "layered",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-07T00:00:00.000Z"
  },
  {
    id: "battle-rise",
    title: "爱的供养",
    source: "built-in",
    fileRef: "/bgm/爱的供养.mp3",
    genres: ["古言", "大结局", "海晏河清"],
    moods: ["释然", "天下太平", "皆大欢喜"],
    scenes: ["大结局", "古风", "皆大欢喜"],
    energy: 0.9,
    darkness: 0.5,
    warmth: 0.4,
    tempo: "slow",
    complexity: "cinematic",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-07T00:00:00.000Z"
  },
  {
    id: "daily-warm",
    title: "Valhalla",
    source: "built-in",
    fileRef: "/bgm/Valhalla.mp3",
    genres: ["校园", "青春", "日常"],
    moods: ["日常", "轻松", "温暖"],
    scenes: ["青春", "校园群像", "肆意"],
    energy: 0.3,
    darkness: 0.1,
    warmth: 0.9,
    tempo: "medium",
    complexity: "ambient",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-07T00:00:00.000Z"
  },
  {
    id: "sad-memory",
    title: "岸边客",
    source: "built-in",
    fileRef: "/bgm/岸边客.mp3",
    genres: ["古言", "权谋", "be"],
    moods: ["回忆", "伤感", "怅然"],
    scenes: ["回忆", "离别", "雨", "生离死别"],
    energy: 0.2,
    darkness: 0.6,
    warmth: 0.3,
    tempo: "slow",
    complexity: "layered",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-07T00:00:00.000Z"
  },
  {
    id: "zhao-yao",
    title: "招摇",
    source: "built-in",
    fileRef: "/bgm/招摇.mp3",
    genres: ["古言", "仙侠", "宿命"],
    moods: ["宿命", "释然", "欢喜"],
    scenes: ["挚友相识", "恋人相认", "重逢"],
    energy: 0.5,
    darkness: 0.5,
    warmth: 0.5,
    tempo: "medium",
    complexity: "ambient",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-11T00:00:00.000Z"
  },
  {
    id: "chun-huo",
    title: "蠢货",
    source: "built-in",
    fileRef: "/bgm/蠢货.mp3",
    genres: ["现言", "恋爱", "甜文"],
    moods: ["甜蜜", "欢喜", "轻松"],
    scenes: ["恋爱", "日常", "告白"],
    energy: 0.5,
    darkness: 0.5,
    warmth: 0.5,
    tempo: "medium",
    complexity: "ambient",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-11T00:00:00.000Z"
  },
  {
    id: "fresh-clothes-youth",
    title: "鲜衣怒马少年郎",
    source: "built-in",
    fileRef: "/bgm/鲜衣怒马少年郎.mp3",
    genres: ["古言", "权谋", "热血"],
    moods: ["热血", "激昂", "宏大"],
    scenes: ["凯旋", "征战", "心怀天下"],
    energy: 0.5,
    darkness: 0.5,
    warmth: 0.5,
    tempo: "medium",
    complexity: "ambient",
    licenseNote: PLACEHOLDER_LICENSE,
    createdAt: "2026-08-11T00:00:00.000Z"
  }
];
